# Generated by Django 6.0.6 on 2026-06-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('lagos', 'Lagos'), ('ibadan', 'Ibadan'), ('abuja', 'Abuja'), ('port_harcourt', 'Port Harcourt')], max_length=20)),
                ('material_name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['material_name', 'city'],
                'unique_together': {('city', 'material_name')},
            },
        ),
    ]
