# Generated by Django 6.0.6 on 2026-06-22 11:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beme', '0001_initial'),
        ('projects', '0003_projectspec'),
    ]

    operations = [
        migrations.CreateModel(
            name='BEMEDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('preliminaries', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('contract_sum', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('preliminaries_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('contingency_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('professional_fees_percent', models.DecimalField(decimal_places=2, default=Decimal('7.50'), max_digits=5)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=Decimal('7.50'), max_digits=5)),
                ('letterhead_company', models.CharField(blank=True, max_length=200)),
                ('letterhead_address', models.CharField(blank=True, max_length=255)),
                ('letterhead_phone', models.CharField(blank=True, max_length=50)),
                ('letterhead_email', models.EmailField(blank=True, max_length=254)),
                ('letterhead_color', models.CharField(blank=True, default='#1f7a40', max_length=20)),
                ('prepared_by', models.CharField(blank=True, max_length=200)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beme_document', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='BEMEElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beme_elements', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BEMELineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_label', models.CharField(blank=True, max_length=5)),
                ('description', models.CharField(max_length=255)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('is_section_header', models.BooleanField(default=False)),
                ('is_provisional_sum', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='beme.bemeelement')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
