# Generated by Django 6.0.6 on 2026-06-21 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('location', models.CharField(choices=[('lagos', 'Lagos'), ('ibadan', 'Ibadan'), ('abuja', 'Abuja'), ('port_harcourt', 'Port Harcourt')], max_length=20)),
                ('building_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('institutional', 'Institutional'), ('industrial', 'Industrial'), ('mixed_use', 'Mixed Use')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
