# Generated by Django 6.0.6 on 2026-06-21 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_floorplanupload_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_type', models.CharField(choices=[('strip', 'Strip Foundation'), ('pad', 'Pad Foundation'), ('raft', 'Raft Foundation'), ('pile', 'Pile Foundation')], max_length=20)),
                ('excavation_depth', models.DecimalField(decimal_places=2, help_text='metres', max_digits=5)),
                ('concrete_grade', models.CharField(choices=[('c15', 'C15'), ('c20', 'C20'), ('c25', 'C25'), ('c30', 'C30')], max_length=10)),
                ('reinforcement_type', models.CharField(choices=[('y10', 'Y10'), ('y12', 'Y12'), ('y16', 'Y16'), ('y20', 'Y20'), ('y25', 'Y25')], max_length=10)),
                ('frame_type', models.CharField(choices=[('framed', 'Framed (Column & Beam)'), ('load_bearing', 'Load-Bearing Blockwork')], max_length=20)),
                ('column_size', models.CharField(help_text='e.g. 225mm x 225mm', max_length=30)),
                ('beam_size', models.CharField(help_text='e.g. 225mm x 450mm', max_length=30)),
                ('slab_thickness', models.DecimalField(decimal_places=1, help_text='mm', max_digits=5)),
                ('wall_type_external', models.CharField(choices=[('sandcrete_225', '225mm Sandcrete Block'), ('sandcrete_150', '150mm Sandcrete Block'), ('brick', 'Brick'), ('drywall', 'Drywall Partition')], max_length=20)),
                ('wall_type_internal', models.CharField(choices=[('sandcrete_225', '225mm Sandcrete Block'), ('sandcrete_150', '150mm Sandcrete Block'), ('brick', 'Brick'), ('drywall', 'Drywall Partition')], max_length=20)),
                ('wall_height', models.DecimalField(decimal_places=2, help_text='metres', max_digits=5)),
                ('roof_type', models.CharField(choices=[('long_span_aluminum', 'Long Span Aluminium'), ('aluminum_step_tile', 'Aluminium Step Tile'), ('asbestos', 'Asbestos'), ('stone_coated_tile', 'Stone-Coated Tile')], max_length=30)),
                ('roof_pitch', models.DecimalField(decimal_places=1, help_text='degrees', max_digits=4)),
                ('truss_type', models.CharField(choices=[('timber', 'Timber Truss'), ('steel', 'Steel Truss')], max_length=10)),
                ('floor_finish', models.CharField(choices=[('terrazzo', 'Terrazzo'), ('tiles', 'Ceramic/Porcelain Tiles'), ('screed', 'Cement Screed'), ('wood', 'Wood/Laminate')], max_length=20)),
                ('wall_finish', models.CharField(choices=[('paint', 'Paint'), ('texture', 'Textured Coating'), ('wallpaper', 'Wallpaper')], max_length=20)),
                ('ceiling_type', models.CharField(choices=[('pop', 'POP (Plaster of Paris)'), ('plywood', 'Plywood'), ('gypsum', 'Gypsum Board')], max_length=20)),
                ('electrical_package', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium (Solar-Ready)')], max_length=20)),
                ('water_supply', models.CharField(choices=[('borehole', 'Borehole'), ('mains', 'Mains/Public Supply'), ('both', 'Borehole + Mains')], max_length=20)),
                ('additional_services', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='projects.project')),
            ],
        ),
    ]
