# Generated by Django 6.0.6 on 2026-06-22 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectspec'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReinforcementSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(choices=[('foundation', 'Foundation'), ('slab', 'Slab'), ('column', 'Column'), ('beam', 'Beam')], max_length=20)),
                ('bar_role', models.CharField(choices=[('main', 'Main'), ('distribution', 'Distribution')], max_length=20)),
                ('bar_size', models.CharField(choices=[('y8', 'Y8'), ('y10', 'Y10'), ('y12', 'Y12'), ('y16', 'Y16'), ('y20', 'Y20'), ('y25', 'Y25'), ('y32', 'Y32')], max_length=10)),
                ('spacing_mm', models.DecimalField(decimal_places=1, max_digits=6)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinforcement_specs', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='StructuralMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('column', 'Column'), ('beam', 'Beam')], max_length=10)),
                ('label', models.CharField(help_text='e.g. C1, B1', max_length=20)),
                ('size', models.CharField(help_text='e.g. 225x225', max_length=30)),
                ('quantity_count', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structural_members', to='projects.project')),
            ],
        ),
    ]
