# Generated by Django 6.0.6 on 2026-06-23 03:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_reinforcementspec_structuralmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspec',
            name='excavation_depth',
            field=models.DecimalField(decimal_places=2, help_text='metres', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.3')), django.core.validators.MaxValueValidator(Decimal('5'))]),
        ),
        migrations.AlterField(
            model_name='projectspec',
            name='roof_pitch',
            field=models.DecimalField(decimal_places=1, help_text='degrees', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('60'))]),
        ),
        migrations.AlterField(
            model_name='projectspec',
            name='slab_thickness',
            field=models.DecimalField(decimal_places=1, help_text='mm', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('75')), django.core.validators.MaxValueValidator(Decimal('500'))]),
        ),
        migrations.AlterField(
            model_name='projectspec',
            name='wall_height',
            field=models.DecimalField(decimal_places=2, help_text='metres', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('2')), django.core.validators.MaxValueValidator(Decimal('6'))]),
        ),
        migrations.AlterField(
            model_name='reinforcementspec',
            name='spacing_mm',
            field=models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('50')), django.core.validators.MaxValueValidator(Decimal('400'))]),
        ),
    ]
