# Generated by Django 6.0.6 on 2026-06-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectspec_excavation_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspec',
            name='concrete_grade',
            field=models.CharField(choices=[('c15', 'C15'), ('c20', 'C20'), ('c25', 'C25'), ('c30', 'C30'), ('c35', 'C35')], max_length=10),
        ),
        migrations.AlterField(
            model_name='projectspec',
            name='reinforcement_type',
            field=models.CharField(choices=[('y8', 'Y8'), ('y10', 'Y10'), ('y12', 'Y12'), ('y16', 'Y16'), ('y20', 'Y20'), ('y25', 'Y25'), ('y32', 'Y32')], max_length=10),
        ),
    ]
