# Generated by Django 6.0.6 on 2026-06-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectspec_concrete_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='confidence',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('manual', 'Manual')], default='medium', max_length=10),
        ),
    ]
