# Generated by Django 6.0.6 on 2026-06-26 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_reinforcement_grade_structural_member_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinforcementspec',
            name='member_count',
            field=models.PositiveIntegerField(blank=True, help_text='Column/Beam quick entry: number of identical members this row applies to, when not linking to a labeled Structural Member.', null=True),
        ),
        migrations.AddField(
            model_name='reinforcementspec',
            name='member_size',
            field=models.CharField(blank=True, help_text='Column/Beam quick entry: e.g. 225x225.', max_length=30),
        ),
        migrations.AlterField(
            model_name='reinforcementspec',
            name='structural_member',
            field=models.ForeignKey(blank=True, help_text='Which labeled member (e.g. C1, B1) this row applies to. For Column/Beam rows, pick this OR fill in Count + Size below — not both. Leave all three blank for Foundation/Slab.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reinforcement_specs', to='projects.structuralmember'),
        ),
    ]
