# Generated by Django 6.0.6 on 2026-06-26 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_reinforcementspec_member_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reinforcementspec',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='reinforcementspec',
            name='member_count',
        ),
        migrations.RemoveField(
            model_name='reinforcementspec',
            name='member_size',
        ),
        migrations.AlterField(
            model_name='reinforcementspec',
            name='structural_member',
            field=models.ForeignKey(blank=True, help_text='Which labeled member (e.g. C1, B1) this row applies to. Required for Column/Beam rows; leave blank for Foundation/Slab.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reinforcement_specs', to='projects.structuralmember'),
        ),
    ]
