# Generated by Django 6.0.6 on 2026-06-26 16:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_reinforcementspec_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='footprint_length_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall building footprint length, in metres — see footprint_width_m.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('200'))]),
        ),
        migrations.AddField(
            model_name='project',
            name='footprint_width_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall building footprint width, in metres — pre-filled from floor plan extraction, editable on the Review Rooms page. Drives perimeter-based quantities (trenches, walls) instead of an estimate. Leave blank to fall back to an estimated footprint.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('200'))]),
        ),
        migrations.AddField(
            model_name='structuralmember',
            name='length_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Column height or beam span, in metres. Leave blank to fall back to wall height (columns) or a flat 4m assumed span (beams) — filling this in gives a more accurate concrete/formwork volume.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.3')), django.core.validators.MaxValueValidator(Decimal('20'))]),
        ),
    ]
