"""
Django settings for structura_ai project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
import dj_database_url

import truststore
from dotenv import load_dotenv

# Delegate TLS certificate verification to the OS-native trust store instead
# of Python's bundled certifi+OpenSSL chain building. Some servers (observed
# with Groq's Cloudflare-fronted API) don't send a complete certificate
# chain in the handshake and rely on clients fetching the missing
# intermediate via AIA — Windows/macOS/Linux's native stacks do this
# automatically, but plain OpenSSL doesn't, causing spurious
# "unable to get local issuer certificate" failures on outbound httpx/
# anthropic SDK calls (floor plan extraction, Struxy chat) on some networks.
# Must run before any ssl-using code, so it's here at the top of settings.py.
truststore.inject_into_ssl()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'projects',
    'beme',
    'struxy',
    'core',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'structura_ai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'structura_ai.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': dj_database_url.parse(config('DATABASE_URL'))
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'projects:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'

AI_PROVIDER = os.environ.get('AI_PROVIDER', 'groq')  # 'groq' or 'anthropic'

ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
ANTHROPIC_VISION_MODEL = 'claude-sonnet-4-6'
ANTHROPIC_CHAT_MODEL = 'claude-sonnet-4-6'

GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')
GROQ_CHAT_MODEL = 'llama-3.3-70b-versatile'
GROQ_VISION_MODEL = 'meta-llama/llama-4-scout-17b-16e-instruct'

SITE_URL = os.environ.get('SITE_URL') or 'http://localhost:8000'

# International format, no '+' or spaces (e.g. 2347037229257), used to build
# the wa.me click-to-chat link on the contact/feedback page.
WHATSAPP_BUSINESS_NUMBER = os.environ.get('WHATSAPP_BUSINESS_NUMBER', '2347037229257')

# Transactional email via Resend's SMTP relay. Falls back to the console
# backend (prints emails to the runserver log) until RESEND_API_KEY is set in
# .env, so signup/password-reset flows still work end-to-end in dev.
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL') or 'DEE STRUCTURA AI <onboarding@resend.dev>'

if RESEND_API_KEY:
    # Resend's HTTPS API, not SMTP — outbound SMTP (587) is commonly blocked
    # on residential/sandboxed networks and several PaaS hosts; HTTPS isn't.
    EMAIL_BACKEND = 'accounts.email_backend.ResendAPIBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
