# Generated by Django 6.0.6 on 2026-06-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[('civil_engineer', 'Civil Engineer'), ('quantity_surveyor', 'Quantity Surveyor'), ('architect', 'Architect'), ('builder_contractor', 'Builder/Contractor'), ('site_manager', 'Site Manager'), ('other', 'Other')], default='civil_engineer', max_length=30),
        ),
    ]
